print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")

# Ejercicio 01
print("    *\n   * *\n  *   *\n *     *\n***   ***\n  *   *\n  *   *\n  *****")

# Ejercicio 02
print("         *")
print("        * *")
print("       *   *")
print("      *     *")
print("     *       *")
print("    *         *")
print("   *            *")
print("  *              *")
print(" *                *")
print("******        ******")
print("     *        *")
print("     *        *")
print("     *        *")
print("     *        *")
print("     **********")

#Ejercicio 03
print("    *     "*2)
print("   * *    "*2)
print("  *   *   "*2)
print(" *     *  "*2)
print("***   *** "*2)
print("  *   *   "*2)
print("  *   *   "*2)
print("  *****   "*2)